### ISSUE TITLE
keeagent icon in tray app is "huge"

### ISSUE THREAD

**Issue by dkebler** [dlech/Keebuntu#50] opened 2017-11-25 19:32 UTC
not sure if this is the tray icon app issue or keeagent but the icon for keyicon is "huge" as DT would say
keepass2-plugin-tray-icon

is the keeagent icon not scalable???

not able to take a screen shot but what should be a bout a 50 or less pixel icon is more like 250 pixels

**Comment by dlech** [comment] 2017-11-25 19:36
Which desktop do you use? Do you install "recommended" packages with apt?

Duplicate of #32?

**Comment by dkebler** [comment] 2017-11-26 01:11
I'm building from a new install 16.04, mint 18.3 which would be gnome 3.   I used your ppa and loaded only the `keepass2-plugin-tray-icon` and `keeagent` packages as I had before with my former install of mint  18.2, 14.04

yes getting the same as #32.  Sorry I didn't see that issue when searching.

**Comment by dkebler** [comment] 2017-11-26 01:26
I had 8:6.8.9.9-7ubuntu5.9 of imagemagick installed already

**Comment by dkebler** [comment] 2017-11-26 01:32
nope switched from tray icon to `keepass2-plugin-application-indicator` package and this same huge keeagent appears.   I'll try tracking down

" The actual package I was referring to is libmagickwandX. Looks like it got bumped to libmagickwand-6.q16-2 in 15.10"

**Comment by dkebler** [comment] 2017-11-26 01:38
here is what is current loaded.  
looks like the name did not change still
libmagickwand-6.q16-2
image manipulation library in 16.04

So what now??

![image](https://user-images.githubusercontent.com/1316185/33236391-d864e124-d206-11e7-9188-af4a354810d7.png)

![image](https://user-images.githubusercontent.com/1316185/33236397-0e4688ce-d207-11e7-8915-0828c5a7de5f.png)

**Comment by dlech** [comment] 2019-03-09 20:44
This should probably be considered a KeeAgent bug. Also gnome-shell-extension-application-indicator should now take care of scaling if the icon is still too big.

**Closed by dlech** 2019-03-09 20:44 UTC
